//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDC
    {
        public long IdCDC { get; set; }
        public long OperationIdUserRef { get; set; }
        public string OperationIP { get; set; }
        public System.DateTime OperationDate { get; set; }
        public short OperationIsDeleted { get; set; }
        public Nullable<short> OperationType { get; set; }
        public string TableName { get; set; }
        public string TablePrimaryKeyName { get; set; }
        public Nullable<long> TableId { get; set; }
        public Nullable<System.Guid> TableIdGuid { get; set; }
        public string Source { get; set; }
    }
}
