//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            this.Town = new HashSet<Town>();
            this.Village = new HashSet<Village>();
            this.Village1 = new HashSet<Village>();
        }
    
        public long IdCity { get; set; }
        public long OperationIdUserRef { get; set; }
        public string OperationIP { get; set; }
        public System.DateTime OperationDate { get; set; }
        public short OperationIsDeleted { get; set; }
        public Nullable<long> IdCountryRef { get; set; }
        public Nullable<int> CityCode { get; set; }
        public string TakbisCityCode { get; set; }
        public string TrafficCode { get; set; }
        public Nullable<System.Guid> DivisionId { get; set; }
        public string CityName { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public System.Data.Entity.Spatial.DbGeometry CityGeometry { get; set; }
        public System.Data.Entity.Spatial.DbGeometry CentroidGeometry { get; set; }
        public System.Data.Entity.Spatial.DbGeometry CentroidCity { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Town> Town { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Village> Village { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Village> Village1 { get; set; }
    }
}
