//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionLog
    {
        public long IdConnectionLog { get; set; }
        public string Username { get; set; }
        public Nullable<long> IdSystemUserRef { get; set; }
        public string IpAddress { get; set; }
        public System.DateTime LogDate { get; set; }
        public short ErrorCode { get; set; }
    }
}
