//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public long IdEvent { get; set; }
        public long OperationIdUserRef { get; set; }
        public string OperationIP { get; set; }
        public System.DateTime OperationDate { get; set; }
        public short OperationIsDeleted { get; set; }
        public string ControllerName { get; set; }
        public string MethodName { get; set; }
        public string FunctionName { get; set; }
        public string EventSource { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<long> ExecutionTime { get; set; }
        public string MachineName { get; set; }
        public string MachineIp { get; set; }
        public string ClientBrowser { get; set; }
    }
}
