//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public long IdPerson { get; set; }
        public long OperationIdUserRef { get; set; }
        public string OperationIP { get; set; }
        public System.DateTime OperationDate { get; set; }
        public short OperationIsDeleted { get; set; }
        public Nullable<long> IdUniversity { get; set; }
        public Nullable<long> IdFaculty { get; set; }
        public Nullable<long> IdUniversityDepartment { get; set; }
        public short EmployeeType { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Title { get; set; }
        public string Profession { get; set; }
        public string Phone { get; set; }
        public string Gsm { get; set; }
        public string About { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Faculties Faculties { get; set; }
        public virtual Universities Universities { get; set; }
        public virtual UniversityDepartment UniversityDepartment { get; set; }
    }
}
