//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleSideMenu
    {
        public long IdRoleSideMenu { get; set; }
        public long OperationIdUserRef { get; set; }
        public string OperationIP { get; set; }
        public System.DateTime OperationDate { get; set; }
        public short OperationIsDeleted { get; set; }
        public Nullable<long> IdRoleRef { get; set; }
        public Nullable<long> IdSideMenuRef { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual SideMenu SideMenu { get; set; }
    }
}
