//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public string Id { get; set; }
        public byte[] Value { get; set; }
        public System.DateTimeOffset ExpiresAtTime { get; set; }
        public Nullable<long> SlidingExpirationInSeconds { get; set; }
        public Nullable<System.DateTimeOffset> AbsoluteExpiration { get; set; }
    }
}
