//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SideMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SideMenu()
        {
            this.RoleSideMenu = new HashSet<RoleSideMenu>();
        }
    
        public long IdSideMenu { get; set; }
        public long OperationIdUserRef { get; set; }
        public string OperationIP { get; set; }
        public System.DateTime OperationDate { get; set; }
        public short OperationIsDeleted { get; set; }
        public Nullable<long> IdParentSideMenu { get; set; }
        public Nullable<long> IdTopMenuRef { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string SideMenuName { get; set; }
        public string SideMenuDescription { get; set; }
        public Nullable<short> SideMenuStatus { get; set; }
        public Nullable<int> SideMenuOrder { get; set; }
        public string IconUrl { get; set; }
        public string ItemBackgroundColor { get; set; }
        public string ItemTextColor { get; set; }
        public string ItemIconColor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleSideMenu> RoleSideMenu { get; set; }
        public virtual TopMenu TopMenu { get; set; }
    }
}
