//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUserRoleParameter
    {
        public long IdSystemUserRoleParameter { get; set; }
        public long OperationIdUserRef { get; set; }
        public string OperationIP { get; set; }
        public System.DateTime OperationDate { get; set; }
        public short OperationIsDeleted { get; set; }
        public Nullable<long> IdSystemUserRef { get; set; }
        public Nullable<long> IdSystemUserRoleRef { get; set; }
        public Nullable<long> IdRoleRef { get; set; }
        public Nullable<bool> ParameterAdmin { get; set; }
        public string SchemaName { get; set; }
        public string TableName { get; set; }
        public Nullable<long> IdParameterRef { get; set; }
        public string Alias { get; set; }
        public string NameColumnRef { get; set; }
        public string ValueColumnRef { get; set; }
    }
}
