//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUserRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemUserRole()
        {
            this.SystemUserRoleLocation = new HashSet<SystemUserRoleLocation>();
        }
    
        public long IdSystemUserRole { get; set; }
        public long OperationIdUserRef { get; set; }
        public string OperationIP { get; set; }
        public System.DateTime OperationDate { get; set; }
        public short OperationIsDeleted { get; set; }
        public long IdSystemUserRef { get; set; }
        public long IdRoleRef { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemUserRoleLocation> SystemUserRoleLocation { get; set; }
    }
}
