//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUserTicket
    {
        public System.Guid IdTicket { get; set; }
        public long IdUserRef { get; set; }
        public System.DateTime OperationDate { get; set; }
    }
}
