//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUserRoleLocation
    {
        public long IdSystemUserRoleLocation { get; set; }
        public long OperationIdUserRef { get; set; }
        public string OperationIP { get; set; }
        public System.DateTime OperationDate { get; set; }
        public short OperationIsDeleted { get; set; }
        public long IdSystemUserRef { get; set; }
        public long IdSystemUserRoleRef { get; set; }
        public Nullable<long> IdCountryRef { get; set; }
        public Nullable<long> IdCityRef { get; set; }
        public Nullable<long> IdTownRef { get; set; }
        public Nullable<long> IdVillageRef { get; set; }
    
        public virtual SystemUserRole SystemUserRole { get; set; }
    }
}
