//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TopMenu()
        {
            this.RoleTopMenu = new HashSet<RoleTopMenu>();
            this.SideMenu = new HashSet<SideMenu>();
        }
    
        public long IdTopMenu { get; set; }
        public long OperationIdUserRef { get; set; }
        public string OperationIP { get; set; }
        public System.DateTime OperationDate { get; set; }
        public short OperationIsDeleted { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string TopMenuName { get; set; }
        public string TopMenuDescription { get; set; }
        public Nullable<short> TopMenuStatus { get; set; }
        public Nullable<int> TopMenuOrder { get; set; }
        public string IconUrl { get; set; }
        public string ItemBackgroundColor { get; set; }
        public string ItemTextColor { get; set; }
        public string ItemIconColor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleTopMenu> RoleTopMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SideMenu> SideMenu { get; set; }
    }
}
