//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Town
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Town()
        {
            this.Village = new HashSet<Village>();
        }
    
        public long IdTown { get; set; }
        public long OperationIdUserRef { get; set; }
        public string OperationIP { get; set; }
        public System.DateTime OperationDate { get; set; }
        public short OperationIsDeleted { get; set; }
        public Nullable<long> IdCityRef { get; set; }
        public Nullable<int> TownCode { get; set; }
        public string TakbisTownCode { get; set; }
        public string TownName { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public Nullable<System.Guid> TownId { get; set; }
        public System.Data.Entity.Spatial.DbGeometry TownGeometry { get; set; }
        public System.Data.Entity.Spatial.DbGeometry CentroidGeometry { get; set; }
        public System.Data.Entity.Spatial.DbGeometry CentroidTown { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Village> Village { get; set; }
    }
}
