//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derin.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Village
    {
        public long IdVillage { get; set; }
        public long OperationIdUserRef { get; set; }
        public string OperationIP { get; set; }
        public System.DateTime OperationDate { get; set; }
        public short OperationIsDeleted { get; set; }
        public Nullable<long> IdTownRef { get; set; }
        public Nullable<long> IdCityRef { get; set; }
        public Nullable<int> VillageCode { get; set; }
        public Nullable<int> TakbisVillageCode { get; set; }
        public Nullable<short> VillageType { get; set; }
        public string VillageName { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public Nullable<System.Guid> TownId { get; set; }
        public Nullable<System.Guid> VillageId { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Centroid_Weighted { get; set; }
        public System.Data.Entity.Spatial.DbGeometry BBox_MinPoint { get; set; }
        public System.Data.Entity.Spatial.DbGeometry BBox_MaxPoint { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Town Town { get; set; }
    }
}
